/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateSubmissionResponse struct {

	Submission *Submission `json:"submission,omitempty"`

	Status string `json:"status,omitempty"`
}
