/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateSubmissionData struct {

	Test bool `json:"test,omitempty"`

	Data *map[string]interface{} `json:"data"`

	Html string `json:"html,omitempty"`

	Css string `json:"css,omitempty"`

	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}
