/*
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateCombinedSubmissionData struct {

	Test bool `json:"test,omitempty"`

	SubmissionIds []string `json:"submission_ids"`

	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	ExpiresIn float32 `json:"expires_in,omitempty"`
}
