# coding: utf-8

"""
    API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import form_api
from form_api.rest import ApiException
from form_api.models.inline_response_201_submission import InlineResponse201Submission


class TestInlineResponse201Submission(unittest.TestCase):
    """ InlineResponse201Submission unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse201Submission(self):
        """
        Test InlineResponse201Submission
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = form_api.models.inline_response_201_submission.InlineResponse201Submission()
        pass


if __name__ == '__main__':
    unittest.main()
