#!/bin/bash
set -e
cd "$(dirname "$0")/../../clients/python"

# It's useful to have access to the original generated tests,
# so we can copy them into our custom specs and modify them.
mv test/test_pdf_api.py test/test_pdf_api.py.original
