/* 
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FormApi.Client.Api;
using FormApi.Client.Model;
using FormApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FormApi.Client.Test
{
    /// <summary>
    ///  Class for testing CreateCombinedSubmissionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateCombinedSubmissionResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateCombinedSubmissionResponse
        //private CreateCombinedSubmissionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCombinedSubmissionResponse
            //instance = new CreateCombinedSubmissionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCombinedSubmissionResponse
        /// </summary>
        [Test]
        public void CreateCombinedSubmissionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateCombinedSubmissionResponse
            //Assert.IsInstanceOfType<CreateCombinedSubmissionResponse> (instance, "variable 'instance' is a CreateCombinedSubmissionResponse");
        }


        /// <summary>
        /// Test the property 'CombinedSubmission'
        /// </summary>
        [Test]
        public void CombinedSubmissionTest()
        {
            // TODO unit test for the property 'CombinedSubmission'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
