/* 
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FormApi.Client.Api;
using FormApi.Client.Model;
using FormApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FormApi.Client.Test
{
    /// <summary>
    ///  Class for testing SubmissionDataRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionDataRequestTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionDataRequest
        //private SubmissionDataRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionDataRequest
            //instance = new SubmissionDataRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionDataRequest
        /// </summary>
        [Test]
        public void SubmissionDataRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionDataRequest
            //Assert.IsInstanceOfType<SubmissionDataRequest> (instance, "variable 'instance' is a SubmissionDataRequest");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'ViewedAt'
        /// </summary>
        [Test]
        public void ViewedAtTest()
        {
            // TODO unit test for the property 'ViewedAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Test]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'AuthType'
        /// </summary>
        [Test]
        public void AuthTypeTest()
        {
            // TODO unit test for the property 'AuthType'
        }
        /// <summary>
        /// Test the property 'AuthSecondFactorType'
        /// </summary>
        [Test]
        public void AuthSecondFactorTypeTest()
        {
            // TODO unit test for the property 'AuthSecondFactorType'
        }
        /// <summary>
        /// Test the property 'AuthProvider'
        /// </summary>
        [Test]
        public void AuthProviderTest()
        {
            // TODO unit test for the property 'AuthProvider'
        }
        /// <summary>
        /// Test the property 'AuthSessionStartedAt'
        /// </summary>
        [Test]
        public void AuthSessionStartedAtTest()
        {
            // TODO unit test for the property 'AuthSessionStartedAt'
        }
        /// <summary>
        /// Test the property 'AuthSessionIdHash'
        /// </summary>
        [Test]
        public void AuthSessionIdHashTest()
        {
            // TODO unit test for the property 'AuthSessionIdHash'
        }
        /// <summary>
        /// Test the property 'AuthUserIdHash'
        /// </summary>
        [Test]
        public void AuthUserIdHashTest()
        {
            // TODO unit test for the property 'AuthUserIdHash'
        }
        /// <summary>
        /// Test the property 'AuthUsernameHash'
        /// </summary>
        [Test]
        public void AuthUsernameHashTest()
        {
            // TODO unit test for the property 'AuthUsernameHash'
        }
        /// <summary>
        /// Test the property 'AuthPhoneNumberHash'
        /// </summary>
        [Test]
        public void AuthPhoneNumberHashTest()
        {
            // TODO unit test for the property 'AuthPhoneNumberHash'
        }

    }

}
