/* 
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FormApi.Client.Api;
using FormApi.Client.Model;
using FormApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FormApi.Client.Test
{
    /// <summary>
    ///  Class for testing SubmissionBatchData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionBatchDataTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionBatchData
        //private SubmissionBatchData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionBatchData
            //instance = new SubmissionBatchData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionBatchData
        /// </summary>
        [Test]
        public void SubmissionBatchDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionBatchData
            //Assert.IsInstanceOfType<SubmissionBatchData> (instance, "variable 'instance' is a SubmissionBatchData");
        }


        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Test]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Test]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'Submissions'
        /// </summary>
        [Test]
        public void SubmissionsTest()
        {
            // TODO unit test for the property 'Submissions'
        }

    }

}
