/* 
 * API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FormApi.Client.Api;
using FormApi.Client.Model;
using FormApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FormApi.Client.Test
{
    /// <summary>
    ///  Class for testing SubmissionDataRequestData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionDataRequestDataTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionDataRequestData
        //private SubmissionDataRequestData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionDataRequestData
            //instance = new SubmissionDataRequestData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionDataRequestData
        /// </summary>
        [Test]
        public void SubmissionDataRequestDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionDataRequestData
            //Assert.IsInstanceOfType<SubmissionDataRequestData> (instance, "variable 'instance' is a SubmissionDataRequestData");
        }


        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

    }

}
