# coding: utf-8

"""
    API V1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import form_api
from form_api.models.submission_batch_data import SubmissionBatchData  # noqa: E501
from form_api.rest import ApiException


class TestSubmissionBatchData(unittest.TestCase):
    """SubmissionBatchData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmissionBatchData(self):
        """Test SubmissionBatchData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = form_api.models.submission_batch_data.SubmissionBatchData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
