# coding: utf-8

"""
    API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import form_api
from form_api.rest import ApiException
from form_api.models.create_submission_body import CreateSubmissionBody


class TestCreateSubmissionBody(unittest.TestCase):
    """ CreateSubmissionBody unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSubmissionBody(self):
        """
        Test CreateSubmissionBody
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = form_api.models.create_submission_body.CreateSubmissionBody()
        pass


if __name__ == '__main__':
    unittest.main()
