/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Data1 model module.
* @module model/Data1
* @version 1.0.0
*/
export default class Data1 {
    /**
    * Constructs a new <code>Data1</code>.
    * @alias module:model/Data1
    * @class
    * @param data {Object} 
    */

    constructor(data) {
        

        
        

        this['data'] = data;

        
    }

    /**
    * Constructs a <code>Data1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Data1} obj Optional instance to populate.
    * @return {module:model/Data1} The populated <code>Data1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Data1();

            
            
            

            if (data.hasOwnProperty('test')) {
                obj['test'] = ApiClient.convertToType(data['test'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} test
    */
    test = undefined;
    /**
    * @member {Object} data
    */
    data = undefined;
    /**
    * @member {Object} metadata
    */
    metadata = undefined;








}


