/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The InlineResponse201CombinedSubmission model module.
* @module model/InlineResponse201CombinedSubmission
* @version 1.0.0
*/
export default class InlineResponse201CombinedSubmission {
    /**
    * Constructs a new <code>InlineResponse201CombinedSubmission</code>.
    * @alias module:model/InlineResponse201CombinedSubmission
    * @class
    * @param id {String}
    * @param expired {Boolean}
    * @param state {module:model/InlineResponse201CombinedSubmission.StateEnum}
    * @param submissionIds {Array.<String>}
    */

    constructor(id, expired, state, submissionIds) {





        this['id'] = id;this['expired'] = expired;this['state'] = state;this['submission_ids'] = submissionIds;


    }

    /**
    * Constructs a <code>InlineResponse201CombinedSubmission</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse201CombinedSubmission} obj Optional instance to populate.
    * @return {module:model/InlineResponse201CombinedSubmission} The populated <code>InlineResponse201CombinedSubmission</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse201CombinedSubmission();





            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('expired')) {
                obj['expired'] = ApiClient.convertToType(data['expired'], 'Boolean');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('submission_ids')) {
                obj['submission_ids'] = ApiClient.convertToType(data['submission_ids'], ['String']);
            }
            if (data.hasOwnProperty('download_url')) {
                obj['download_url'] = ApiClient.convertToType(data['download_url'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Boolean} expired
    */
    expired = undefined;
    /**
    * @member {String} expires_at
    */
    expires_at = undefined;
    /**
    * @member {module:model/InlineResponse201CombinedSubmission.StateEnum} state
    */
    state = undefined;
    /**
    * @member {Object} metadata
    */
    metadata = undefined;
    /**
    * @member {Array.<String>} submission_ids
    */
    submission_ids = undefined;
    /**
    * @member {String} download_url
    */
    download_url = undefined;






    /**
    * Allowed values for the <code>state</code> property.
    * @enum {String}
    * @readonly
    */
    static StateEnum = {

        /**
         * value: "pending"
         * @const
         */
        "pending": "pending",

        /**
         * value: "processed"
         * @const
         */
        "processed": "processed",

        /**
         * value: "error"
         * @const
         */
        "error": "error"
    };



}


