#!/bin/bash
set -e
cd "$(dirname "$0")/../../clients/csharp"

# It's useful to have access to the original generated tests,
# so we can copy them into our custom specs and modify them.
mv src/FormApi.Client.Test/Api/PDFApiTests.cs src/FormApi.Client.Test/Api/PDFApiTests.cs.original
