#!/bin/bash
set -e
cd "$(dirname "$0")/../../clients/php"

# It's useful to have access to the original generated tests,
# so we can copy them into our custom specs and modify them.
mv test/Api/PDFApiTest.php test/Api/PDFApiTest.php.original
