#!/bin/bash
set -e
cd "$(dirname "$0")/../.."
VERSION=$(cat config/php.json | jq -r .artifactVersion)
cd "./clients/php"

if ! [ -d .git ]; then
  git init
  git remote add origin git@github.com:FormAPI/formapi-php.git
  git fetch origin
  git reset --hard origin/master
  echo "Pulled FormAPI/formapi-php from GitHub and reset to master branch."
  echo "Please re-run the generator script, then run ./scripts/php/release again"
  echo "to commit the changes."
  exit 1
fi

echo "vendor" > .gitignore

COMMIT_MESSAGE="Update on $(date "+%F %T"). Version: $VERSION"
git add -A
git commit -m "$COMMIT_MESSAGE"
echo "Committed changes with message: $COMMIT_MESSAGE"
# Need to tag the new version, otherwise it's not picked up by packagist
# (If tag already exists, then the script will crash at this point.)
git tag "v$VERSION"

git push origin master -f
git push origin "v$VERSION"
