#!/bin/bash
set -e

cd "$(dirname "$0")/../../clients/php"

if ! [ -d .git ]; then
  git init
  git remote add origin git@github.com:FormAPI/formapi-php.git
  git fetch origin
  git reset --hard origin/master
  echo "Pulled FormAPI/formapi-php from GitHub and reset to master branch."
  echo "Please re-run the generater script, then run ./scripts/php/release again"
  echo "to commit the changes."
  exit 1
fi

echo "vendor" > .gitignore

VERSION=$(cat composer.json | grep '"version":' | sed 's/\s*"version": "\|",//g')

COMMIT_MESSAGE="Update on $(date). Version: $VERSION"
git add -A
git commit -m "$COMMIT_MESSAGE"
echo "Committed changes with message: $COMMIT_MESSAGE"

git push origin master -f
