#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

echo "Removing trailing whitespace..."
find form_api -name "*.py" -type f -exec sed -E -i 's/[[:space:]]+$//g' {} +

echo "Injecting extensions..."
sed -i "s/from .apis.pdf_api import PDFApi/\
from .apis.pdf_api import PDFApi\nfrom .apis.client import Client/" \
form_api/__init__.py

echo "Adding library details..."
sed -i "s/description=\"API V1\",/description=\"FormAPI Client\",/" setup.py
sed -i "s/author_email=\"\",/author_email=\"support@formapi.io\",/" setup.py
sed -i "s/url=\"\",/url=\"https:\/\/formapi.io\",/" setup.py
sed -i "s/keywords=\[\"Swagger\", \"API V1\"\],/keywords=[\"FormAPI\", \"PDF\", \"forms\"],/" setup.py


cp extensions/form_api/apis/client.py form_api/apis
