# coding: utf-8

"""
    API V1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Submission(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'test': 'bool',
        'expired': 'bool',
        'expires_at': 'str',
        'processed_at': 'str',
        'state': 'str',
        'metadata': 'object',
        'download_url': 'str',
        'batch_id': 'str',
        'data_requests': 'list[SubmissionDataRequest]'
    }

    attribute_map = {
        'id': 'id',
        'test': 'test',
        'expired': 'expired',
        'expires_at': 'expires_at',
        'processed_at': 'processed_at',
        'state': 'state',
        'metadata': 'metadata',
        'download_url': 'download_url',
        'batch_id': 'batch_id',
        'data_requests': 'data_requests'
    }

    def __init__(self, id=None, test=None, expired=None, expires_at=None, processed_at=None, state=None, metadata=None, download_url=None, batch_id=None, data_requests=None):  # noqa: E501
        """Submission - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._test = None
        self._expired = None
        self._expires_at = None
        self._processed_at = None
        self._state = None
        self._metadata = None
        self._download_url = None
        self._batch_id = None
        self._data_requests = None
        self.discriminator = None

        self.id = id
        self.test = test
        self.expired = expired
        if expires_at is not None:
            self.expires_at = expires_at
        if processed_at is not None:
            self.processed_at = processed_at
        self.state = state
        if metadata is not None:
            self.metadata = metadata
        if download_url is not None:
            self.download_url = download_url
        if batch_id is not None:
            self.batch_id = batch_id
        if data_requests is not None:
            self.data_requests = data_requests

    @property
    def id(self):
        """Gets the id of this Submission.  # noqa: E501


        :return: The id of this Submission.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Submission.


        :param id: The id of this Submission.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def test(self):
        """Gets the test of this Submission.  # noqa: E501


        :return: The test of this Submission.  # noqa: E501
        :rtype: bool
        """
        return self._test

    @test.setter
    def test(self, test):
        """Sets the test of this Submission.


        :param test: The test of this Submission.  # noqa: E501
        :type: bool
        """
        if test is None:
            raise ValueError("Invalid value for `test`, must not be `None`")  # noqa: E501

        self._test = test

    @property
    def expired(self):
        """Gets the expired of this Submission.  # noqa: E501


        :return: The expired of this Submission.  # noqa: E501
        :rtype: bool
        """
        return self._expired

    @expired.setter
    def expired(self, expired):
        """Sets the expired of this Submission.


        :param expired: The expired of this Submission.  # noqa: E501
        :type: bool
        """
        if expired is None:
            raise ValueError("Invalid value for `expired`, must not be `None`")  # noqa: E501

        self._expired = expired

    @property
    def expires_at(self):
        """Gets the expires_at of this Submission.  # noqa: E501


        :return: The expires_at of this Submission.  # noqa: E501
        :rtype: str
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this Submission.


        :param expires_at: The expires_at of this Submission.  # noqa: E501
        :type: str
        """

        self._expires_at = expires_at

    @property
    def processed_at(self):
        """Gets the processed_at of this Submission.  # noqa: E501


        :return: The processed_at of this Submission.  # noqa: E501
        :rtype: str
        """
        return self._processed_at

    @processed_at.setter
    def processed_at(self, processed_at):
        """Sets the processed_at of this Submission.


        :param processed_at: The processed_at of this Submission.  # noqa: E501
        :type: str
        """

        self._processed_at = processed_at

    @property
    def state(self):
        """Gets the state of this Submission.  # noqa: E501


        :return: The state of this Submission.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Submission.


        :param state: The state of this Submission.  # noqa: E501
        :type: str
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501
        allowed_values = ["pending", "processed", "invalid_data", "error", "image_download_failed", "image_processing_failed", "waiting_for_data_requests"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def metadata(self):
        """Gets the metadata of this Submission.  # noqa: E501


        :return: The metadata of this Submission.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this Submission.


        :param metadata: The metadata of this Submission.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def download_url(self):
        """Gets the download_url of this Submission.  # noqa: E501


        :return: The download_url of this Submission.  # noqa: E501
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """Sets the download_url of this Submission.


        :param download_url: The download_url of this Submission.  # noqa: E501
        :type: str
        """

        self._download_url = download_url

    @property
    def batch_id(self):
        """Gets the batch_id of this Submission.  # noqa: E501


        :return: The batch_id of this Submission.  # noqa: E501
        :rtype: str
        """
        return self._batch_id

    @batch_id.setter
    def batch_id(self, batch_id):
        """Sets the batch_id of this Submission.


        :param batch_id: The batch_id of this Submission.  # noqa: E501
        :type: str
        """

        self._batch_id = batch_id

    @property
    def data_requests(self):
        """Gets the data_requests of this Submission.  # noqa: E501


        :return: The data_requests of this Submission.  # noqa: E501
        :rtype: list[SubmissionDataRequest]
        """
        return self._data_requests

    @data_requests.setter
    def data_requests(self, data_requests):
        """Sets the data_requests of this Submission.


        :param data_requests: The data_requests of this Submission.  # noqa: E501
        :type: list[SubmissionDataRequest]
        """

        self._data_requests = data_requests

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Submission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
