#!/bin/sh
set -e
cd "$(dirname "$0")/.."

LANGUAGE="$1"
CONFIG_FILE="swagger-config.json"

if [ "$LANGUAGE" = "" ]; then
  ./script/swagger # prints languages
  exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Could not find $CONFIG_FILE"
  ./script/swagger config-help -l "$LANGUAGE"
  exit 1
fi

./script/clean

./script/swagger generate \
  -i ../form_api/swagger/v1/swagger.json \
  -l "$LANGUAGE" \
  -c "$CONFIG_FILE"

# call a generator cleanup script
if [ -f "script/post_generate_language" ]; then
  ./script/post_generate_language
fi


# Inject extensions
sed -i "s/require 'form_api\/api\/pdf_api'/\
require File.join(File.dirname(__FILE__), '..\/extensions\/lib\/form_api\/api\/client')/" \
lib/form_api.rb
