#!/bin/bash
set -e
cd "$(dirname "$0")/../"

echo "Building formapi-generator..."
# Sometimes we need to refresh java packages by building openapi-generator first.
./scripts/build-formapi-generator || (
  ./scripts/build-openapi-generator && ./scripts/build-formapi-generator)

LANGUAGE="$1"

if [ -z "$LANGUAGE" ]; then
  for f in config/*; do
    LANGUAGE="$(echo $f | sed -e "s/config\///g" -e "s/\.json//g")"
    if [ "$LANGUAGE" = "java" ]; then
      echo "Skipping $LANGUAGE for now, not implemented yet."
      continue
    fi
    ./scripts/generate "$LANGUAGE"
    ./scripts/run_integration_tests "$LANGUAGE"
  done
  exit
fi

./scripts/generate "$LANGUAGE"
./scripts/run_integration_tests "$LANGUAGE"
