#!/bin/sh
set -e
cd "$(dirname "$0")/.."

LANGUAGE=ruby
CONFIG_FILE="swagger-config.json"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Could not find $CONFIG_FILE"
  ./scripts/swagger config-help -l "$LANGUAGE"
  exit 1
fi

./scripts/clean

./scripts/swagger generate \
  -i ../form_api/swagger/v1/swagger.json \
  -l "$LANGUAGE" \
  -c "$CONFIG_FILE"

# call a generator cleanup script
./scripts/post_generate
