#!/bin/bash
set -e
cd "$(dirname "$0")/.."

LANGUAGE="$1"
CONFIG_FILE="swagger-config.$LANGUAGE.json"
CLIENT_DIR="clients/$LANGUAGE"

if [ -z "$LANGUAGE" ]; then
  for LANG in ruby python java php javascript; do # go rust elixir swift4 objc
    echo "Generating $LANG client library..."
    ./scripts/generate "$LANG"
  done
  exit
fi

case "$LANGUAGE" in
  ruby)
    GENERATOR_NAME="formapi-ruby";;
  python)
    GENERATOR_NAME="formapi-python";;
  php)
    GENERATOR_NAME="formapi-php";;
  *)
    GENERATOR_NAME="$LANGUAGE";;
esac

mkdir -p "examples/$LANGUAGE"
mkdir -p "scripts/$LANGUAGE"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Could not find $CONFIG_FILE"
  ./openapi-generator-cli config-help -l "$LANGUAGE"
  exit 1
fi

case "$LANGUAGE" in
  php)
    # Preserve installed libraries in vendor
    for f in $CLIENT_DIR/*; do
      if ! [[ "$f" = *'/vendor' ]]; then rm -r $f; fi
    done;;
  *)
    rm -rf "$CLIENT_DIR"
esac


./openapi-generator-cli generate \
  --input-spec ../form_api/swagger/v1/swagger.json \
  --generator-name "$GENERATOR_NAME" \
  --config "$CONFIG_FILE" \
  --output "$CLIENT_DIR"

# cd "$CLIENT_DIR"
# find . -not -path './.git/*' -type f -exec sed -E -i 's/[[:space:]]+$//g' {} +

# git init
# git add -A
# git commit -m "Initial commit"

# if [ -f "../../patches/$LANGUAGE.diff" ]; then
#   if ! git apply --check "../../patches/$LANGUAGE.diff"; then
#     echo "Could not apply patch: ../../patches/$LANGUAGE.diff. Please fix the conflicts."
#     exit 1
#   fi

#   git apply "../../patches/$LANGUAGE.diff"
#   git add -A
#   git commit -m "Applied patch"

#   if [ -f "../../scripts/$LANGUAGE/install_deps" ]; then
#     ../../scripts/$LANGUAGE/install_deps
#   fi
# elif [ -f "../../scripts/$LANGUAGE/post_generate" ]; then
#   ../../scripts/$LANGUAGE/post_generate
#   find . -not -path './.git/*' -type f -exec sed -E -i 's/[[:space:]]+$//g' {} +

#   git add -A
#   git commit -m "Ran post_generate script"

#   cd ../..
#   ./scripts/update-patch $LANGUAGE
# fi
