#!/bin/bash
# I always forget to regenerate the API clients after bumping the versions.
# So I'll do that in here too.
set -e
cd "$(dirname "$0")/.."

LANGUAGE="$1"

generate_and_release() {
  echo "==> Generating $1 client library..."
  ./scripts/generate "$1"
  echo "==> Committing changes..."
  ./scripts/commit_changes "$1"
  echo "==> Building and releasing new version..."
  ./scripts/$1/release
  echo "==> Pushing to GitHub..."
  ./scripts/push_to_github "$1"
  echo "==> Finished!"
}

if [ -n "$LANGUAGE" ]; then
  generate_and_release "$LANGUAGE"
  exit
fi

for f in config/*; do
  LANGUAGE="$(echo $f | sed -e "s/config\///g" -e "s/\.json//g")"
  generate_and_release "$LANGUAGE"
done
