#!/bin/bash
# I always forget to regenerate the API clients after bumping the versions.
# So I'll do that in here too.
set -e
cd "$(dirname "$0")/.."

LANGUAGE="$1"

generate_and_release() {
  ./scripts/generate "$1"
  echo "Releasing new version of $1 client library..."
  ./scripts/$1/release
}

if [ -n "$LANGUAGE" ]; then
  generate_and_release "$LANGUAGE"
  exit
fi

for f in config/*; do
  LANGUAGE="$(echo $f | sed -e "s/config\///g" -e "s/\.json//g")"
  if [ "$LANGUAGE" = "java" ]; then
    echo "Skipping $LANGUAGE for now, not implemented yet."
    continue
  fi
  generate_and_release "$LANGUAGE"
done
