#!/bin/bash
set -e
cd "$(dirname "$0")/.."

LANGUAGE="$1"

if [ -n "$LANGUAGE" ]; then
  ./scripts/$LANGUAGE/release
  exit
fi

for f in config/*; do
  LANGUAGE="$(echo $f | sed -e "s/config\///g" -e "s/\.json//g")"
  if [ "$LANGUAGE" = "java" ]; then
    echo "Skipping $LANGUAGE for now, not implemented yet."
    continue
  fi
  echo "Releasing new version of $LANGUAGE client library..."
  ./scripts/$LANGUAGE/release
done
