#!/bin/bash
set -e
cd "$(dirname "$0")/.."

LANGUAGE="$1"

if [ -z "$LANGUAGE" ]; then
  for f in config/*; do
    LANG="$(echo $f | sed -e "s/config\///g" -e "s/\.json//g")"
    ./scripts/tag_version "$LANG"
  done
  exit
fi

VERSION="$(./scripts/get_version $LANG)"
GIT_TAG="$LANGUAGE-$VERSION"

if git rev-parse -q --verify "refs/tags/$GIT_TAG" > /dev/null; then
  echo "$GIT_TAG tag already exists!"
  exit
fi

echo "Tagging current commit with: $GIT_TAG"
git tag "$GIT_TAG"
