#!/bin/bash
set -e
cd "$(dirname "$0")/.."

LANGUAGE="$1"
CLIENT_DIR="clients/$LANGUAGE"

if [ -z "$LANGUAGE" ]; then
  for d in clients/*; do
    LANGUAGE=${d/clients\//}
    echo "Updating patch for $LANGUAGE client library..."
    ./scripts/update-patch "$LANGUAGE"
  done
  exit
fi

if [ ! -d "$CLIENT_DIR/.git" ]; then
  echo "$CLIENT_DIR is not a git repository"
  exit 1
fi

echo "Creating patch for $CLIENT_DIR => ../../patches/$LANGUAGE.diff"

cd "$CLIENT_DIR"

INITIAL_COMMIT=$(git rev-list --max-parents=0 HEAD)
git format-patch $INITIAL_COMMIT --stdout > ../../patches/$LANGUAGE.diff
