#!/bin/bash
set -e
cd "`dirname \"$0\"`/../../clients/java"

if [[ $1 != *".java" ]]; then
  echo "Must be called with a .java file."
  exit 1
fi

class_name=`basename -s .java $1`

export CLASSPATH=".:$PWD/target/*:$PWD/target/lib/*"

javac $1

cd `dirname $1`
java $class_name
