#!/bin/sh
set -e

cd "`dirname \"$0\"`"
# ./build

cd "../../clients/java/src/test"

# runs a test file with PASS/FAIL message
run_test() {
  ../../../../scripts/java/run_java_file $PWD/$1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(find -type f -name *.java); do
    run_test $test
  done
else
  run_test $1.java
fi
