#!/bin/bash
set -e
cd "$(dirname "$0")/../../clients/ruby"

# It's useful to have access to the original generated tests,
# so we can copy them into our custom specs and modify them.
mv spec/api/pdf_api_spec.rb spec/api/pdf_api_spec_original.skipped.rb
