#!/bin/sh
set -e
cd "`dirname \"$0\"`/../../clients/ruby"

# check dependencies
ruby -v > /dev/null    || (echo "ruby must be installed"; exit 1)
bundler -v > /dev/null || (echo "bundler must be installed"; exit 1)

bundle install --quiet

# run tests
rspec
