#!/bin/bash
set -e
cd "$(dirname "$0")/../../clients/javascript"

# It's useful to have access to the original generated tests,
# so we can copy them into our custom specs and modify them.
mv test/api/PDFApi.spec.js test/api/PDFApi.spec.js.original
